import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/bodyComponents/layout/Navbar";
import Footer from "./components/bodyComponents/layout/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en">
      <body className=" ">
        <Navbar />
        <main className="relative">
        {children}
        </main>
        <Footer />
        
        </body>
    </html>
  );
}
